### PR TITLE
Create new attach.obj with 200 trigs

### PR DESCRIPTION
**Pull request by Phrohdoh**
screen shot 2015-09-05 at 11 20 46 am

### CODE REVIEW

**Comment by RobotCaleb** [comment]
I'm out. Could you include a screenshot in the PR?

**Comment by Phrohdoh** [comment]
@RobotCaleb done.

**Comment by RobotCaleb** [comment]
Looks upside down.

image

**Comment by Phrohdoh** [comment]
Okay, I'm done.

**Pull request closed without merging**
