### PR TITLE
mesh: Use less exotic vertex format, to avoid angering AMD

### PR DESCRIPTION
**Pull request by chrisforbes**
Signed-off-by: Chris Forbes <chrisf@ijw.co.nz>

### CODE REVIEW

**Comment by chrisforbes** [comment]
This whole thing just makes me sad.

**Comment by mkfifo** [comment]
I don't have the knowledge to verify the code change, but visually there are no obvious regressions for me (intel hda).

**Comment by MicroJOo** [comment]
i can run it now , and it works in the room ... outside of the room it looks like this : 
(also , i want to point out , that my cpu is getting damn hot while running EN)

dig

**Comment by RobotCaleb** [comment]
No longer crashes. Skybox fails to render, as seen in @MicroJOo screenshot

**Pull request merged**
