### PR TITLE
Components

### PR DESCRIPTION
**Pull request by RobotCaleb**
This is a big change. Anyone is free to look at it, but I'm going to assign @chrisforbes as he is already pretty familiar with all of the code.

Featured here is a component entity system, components hooked up to our entities, and the old entity struct partially gutted.
Projectiles have been revamped to use contiguous chunks of memory for storage. This is based on, but not coupled with, the component memory pooling.

### CODE REVIEW

**Comment by chrisforbes** [comment]
Needs tweaking to pass travis.

**Comment by RobotCaleb** [comment]
Okay, travis fixed and rebased.

**Comment by mkfifo** [comment]
wwwwoooooowwwwwww

**Comment by chrisforbes** [comment]
Good to go, I think

**Pull request merged**
