### PR TITLE
Input bind configuration files

### PR DESCRIPTION
**Pull request by RobotCaleb**
This is a placeholder for the input binding configuration file work.

Please leave comments as needed.

At time of writing this won't build on linux due to new dependency on libconfig that isn't in the cmake targets.

### CODE REVIEW

**Comment by mkfifo** [comment]
Currently not building due to libconfig missing from deps, I have added this support in my repo and the build is still failing as we are building with -Wall (set at top of CMakeLists.txxt file if UNIX, need to figure out how to set it for your compilre)

We aim to keep warnings at a minimum, it seems you have some warnings and errors there:

```
[ 92%] Building CXX object CMakeFiles/nightmare.dir/main.cc.o
/home/chris/devel/engineers-nightmare/main.cc: In function ‘void init()’:
/home/chris/devel/engineers-nightmare/main.cc:853:59: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘long unsigned int’ [-Wformat=]
     printf("World vertex size: %u bytes\n", sizeof(vertex));
                                                           ^
/home/chris/devel/engineers-nightmare/main.cc: In function ‘void cycle_slot(slot_cycle_direction)’:
/home/chris/devel/engineers-nightmare/main.cc:1581:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (cur_slot >= num_tools) {
                      ^
/home/chris/devel/engineers-nightmare/main.cc: In function ‘void configureBindings()’:
/home/chris/devel/engineers-nightmare/main.cc:1664:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (unsigned int i = 0; i < count; ++i) {
                                    ^
/home/chris/devel/engineers-nightmare/main.cc:1672:58: error: ‘config_setting_lookup’ was not declared in this scope
             inputs = config_setting_lookup(bind, "inputs");
                                                          ^
/home/chris/devel/engineers-nightmare/main.cc:1676:60: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (unsigned int input_index = 0; input_index < inputs_count; ++input_index) {
                                                            ^
/home/chris/devel/engineers-nightmare/main.cc:1668:39: warning: unused variable ‘input_name’ [-Wunused-variable]
             const char *action_name, *input_name;
                                       ^
In file included from /usr/include/bullet/LinearMath/btVector3.h:21:0,
                 from /usr/include/bullet/BulletCollision/CollisionDispatch/btCollisionWorld.h:80,
                 from /usr/include/bullet/btBulletCollisionCommon.h:22,
                 from /usr/include/bullet/btBulletDynamicsCommon.h:20,
                 from /home/chris/devel/engineers-nightmare/src/physics.h:3,
                 from /home/chris/devel/engineers-nightmare/main.cc:27:
```

I have fixed all the warnings on my branch, however the error

```
/home/chris/devel/engineers-nightmare/main.cc:1672:58: error: ‘config_setting_lookup’ was not declared in this scope
             inputs = config_setting_lookup(bind, "inputs");
```

Is interesting as it seems `config_setting_lookup` doesn't exist in eithher `libconfig8` (`libconfig++9-dev`) nor in `libconfig9` (`libconfig++8-dev`) despite it being mentioned in the docs http://www.hyperrealm.com/libconfig/libconfig_manual.html#index-config_005fsetting_005flookup


Until we sort out this dep. this will not build on linux so I cannot merge this in.

**Comment by mkfifo** [comment]
ahh cmake pkg search was also not updated

**Comment by mkfifo** [comment]
I have tried both version 8 and 9

```
chris@heimdall:~/devel/engineers-nightmare$ apt-cache policy libconfig8-dev
libconfig8-dev:
  Installed: 1.4.9-2
  Candidate: 1.4.9-2
  Version table:
 *** 1.4.9-2 0
        500 http://ftp.nz.debian.org/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     1.4.8-5 0
        500 http://ftp.nz.debian.org/debian/ wheezy/main amd64 Packages
        500 http://http.debian.net/debian/ wheezy/main amd64 Packages
```

```
chris@heimdall:~/devel/engineers-nightmare$ dpkg --get-selections | grep libconfig
libconfig-dev:amd64				install
libconfig-doc					install
libconfig9:amd64				install
```

interestingly if I look at the include file I can confirm that it doesn't exist

```
chris@heimdall:~/devel/engineers-nightmare$ grep 'config_setting_lookup' /usr/include/libconfig.h
extern LIBCONFIG_API int config_setting_lookup_int(
extern LIBCONFIG_API int config_setting_lookup_int64(
extern LIBCONFIG_API int config_setting_lookup_float(
extern LIBCONFIG_API int config_setting_lookup_bool(
extern LIBCONFIG_API int config_setting_lookup_string(
```

**Comment by mkfifo** [comment]
The function in question `config_setting_lookup` was called `config_setting_lookup_from` up to version 1.4.9, see http://upstream-tracker.org/diffs/libconfig/1.4.9_to_1.5/diff.html

**Comment by chrisforbes** [comment]
Let's go with the 1.4 API if we can. Even Arch doesn't have 1.5 yet.

On Sun, May 24, 2015 at 12:12 PM, Chris Hall (cjh) <notifications@github.com

**Comment by mkfifo** [comment]
I added a shim in to allow it to build on both, simple #define

**Comment by mkfifo** [comment]
Closing this as I have made #109 which subsumes this.

**Pull request closed without merging**
