### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by RobotCaleb**
Fix heap issues caused by my negligence.
ship->ensure_* calls now return requested.
components into own files.
const parameters corrected.

### CODE REVIEW

**Comment by chrisforbes** [comment]
Travis is upset about your memcpy/memset in some of the files.

**Comment by RobotCaleb** [comment]
Thanks, try that.

**Comment by RobotCaleb** [comment]
Rebased on master after frame_data merge.

**Comment by RobotCaleb** [comment]
Two more changes.

**Pull request merged**
