### PR TITLE
Server common work

### PR DESCRIPTION
**Pull request by RobotCaleb**
I took @mikeyhc server_common branch and cherry picked my windows build changes that were against his prior networking branch. I then rebased this against master.

This was a bit of a mess to get brought up and running on windows.
Not all of it makes me happy, but I'd rather have it in and fix the issues than keep kicking the can down the road.

I have not tested this client on linux. The server I have tested and verified that it seems to work when connected to from a windows client.

Please, pick all the nits.

### CODE REVIEW

**Comment by RobotCaleb** [comment]
This needs to come with engineers-nightmare/windows-dependencies#4

**Comment by chrisforbes** [comment]
:+1:

**Comment by RobotCaleb** [comment]
Rebased and modernized.
I believe there's an issue in the server's tracking of topo space, but it's too late for me to figure it out.

**Comment by chrisforbes** [comment]
Broke this again by merging #383, needs rebase.

**Comment by RobotCaleb** [comment]
:fireworks: (fixed)

**Comment by chrisforbes** [comment]
Merged, will address fallout as we find it.

**Pull request merged**
